use san_agustin;
select  * from usuarios;
select *  from Indicadores;
select * from objsigecalidad;
select * from formulariobase; 

INSERT INTO `san_agustin`.`objsigecalidad` (`ID_OSGC`, `NOMBRE_OSGC`, `DESCRIPCION_OSGC`) 
VALUES ('1', 'GARANTIZAR LA GESTIÓN ACADÉMICA (SGC)', 'GARANTIZAR LA GESTIÓN ACADÉMICA (SGC)'),
('2', 'CONSOLIDAR LOS PROYECTOS PESA+ EN FUNCIONAMIENTO Y GENERAR NUEVOS DE ACUERDO A LOS 5 COMPONENTES DEL PLAN ESTRATÉGICO (SGC)', 'CONSOLIDAR LOS PROYECTOS PESA+ EN FUNCIONAMIENTO Y GENERAR NUEVOS DE ACUERDO A LOS 5 COMPONENTES DEL PLAN ESTRATÉGICO (SGC)'),
('3', 'OPTIMIZAR EL DESEMPEÑO HOLÍSTICO DEL DOCENTE (SGC)', 'OPTIMIZAR EL DESEMPEÑO HOLÍSTICO DEL DOCENTE (SGC).'),
('4', 'AFIANZAR LA FORMACIÓN INTEGRAL DE LOS ESTUDIANTES (SGC).', 'AFIANZAR LA FORMACIÓN INTEGRAL DE LOS ESTUDIANTES (SGC).');


INSERT INTO `san_agustin`.`Indicadores` (`ID`, `ID_OBJACADEMICO`, `ID_OSGC`, `ID_LINEABASE`, `ID_FORM`, `NOMBRE_IDEA`) 
VALUES ('1', '1', '1', '1', '1', '1', 'Nivel de cumplimiento en la entrega de documentos requeridos por autoridades educativas para el cierre e inicio de gestión.'),
('2', '1', '1', '1', '1', '1', 'Tasa de cumplimiento en la entrega de Plan Curricular - Contenidos (PC-C).'),
('3', '1', '1', '1', '1', '1', 'Tasa de cumplimiento en la entrega de Plan Global Operativo (PGO) bajo los lineamientos definidos.'),
('4', '1', '1', '1', '1', '1', 'Tasa de cumplimiento en la publicación en plataforma de Plan Curricular - Contenidos por profesores trimestralmente.'),
('5', '1', '1', '1', '1', '1', 'Nivel de publicación de materiales y recursos educativos en plataforma.'),
('6', '1', '1', '1', '1', '1', 'Índice de cumplimiento de avance curricular por períodos.'),
('7', '1', '1', '1', '1', '1', 'Tasa de cumplimiento en la entrega de notas por período.'),
('8', '1', '1', '1', '1', '1', 'Nivel de cumplimiento en la entrega de Reporte Académico de Alerta Temprana (RAAT).'),
('9', '1', '1', '1', '1', '1', 'Nivel de cobertura de uso docente del Sistema Informático de Gestión Académica (SIGA).'),
('10', '1', '1', '1', '1', '1', 'Nivel de cobertura de acceso al SIGA de parte de estudiantes y familias.'),
('11', '1', '1', '1', '1', '1', 'Índice de asistencia de estudiantes por trimestre.'),
('12', '1', '1', '1', '1', '1', 'Índice de licencias de estudiantes por trimestre (registradas).'),
('13', '1', '1', '1', '1', '1', 'Índice de incidencias de estudiantes por trimestre (registradas).'),
('14', '1', '1', '1', '1', '1', 'Nivel de cumplimiento en la actualización del registro de notas en el SIGA.'),
('15', '1', '1', '1', '1', '1', 'Cantidad de comunicados enviados por coordinadores y docentes trimestralmente.'),
('16', '1', '1', '1', '1', '1', 'Cantidad de comunicados publicados según medios oficiales contemplados en la estrategia comunicacional.'),
('17', '1', '1', '1', '1', '1', 'Cantidad de productos audiovisuales curriculares generados.'),
('18', '1', '1', '1', '1', '1', 'Cantidad de productos audiovisuales extracurriculares generados.'),
('19', '1', '1', '1', '1', '1', 'Cantidad de reuniones realizadas por el EGE.'),
('20', '1', '1', '1', '1', '1', 'Cantidad de reuniones realizadas EGE-plantel docente.'),
('21', '1', '1', '1', '1', '1', 'Cantidad de reuniones realizadas EGE-representantes estudiantiles.'),
('22', '1', '1', '1', '1', '1', 'Media de reuniones desarrolladas entre coordinadores y familias.'),
('23', '1', '1', '1', '1', '1', 'Tasa de uso docente del sistema de formación híbrida.'),
('24', '1', '1', '1', '1', '1', 'Cantidad de actividades sincrónicas y asincrónicas desarroladas por docentes.'),
('25', '1', '1', '1', '1', '1', 'Nivel de funcionamiento general del sistema de formación híbrida.'),
('26', '1', '1', '1', '1', '1', 'Nivel de cumplimiento en la presentación de resultados por indicador de acuerdo a plazos establecidos.'),
('27', '1', '1', '1', '1', '1', 'Cantidad de recursos educativos editoriales producidos por los docentes: sumA.'),
('28', '1', '1', '1', '1', '1', 'Cantidad de recursos educativos editoriales producidos por los docentes: Segmento y Examen.'),
('29', '1', '1', '1', '1', '1', 'Cantidad de Segmentos y Examen concluidos por los estudiantes.'),
('30', '1', '1', '1', '1', '1', 'Nivel de ingreso en el área de inglés.'),
('31', '1', '1', '1', '1', '1', 'Cantidad de horas de trabajo conversacional en inglés por estudiante (1ro a 6to de secundaria).'),
('32', '1', '1', '1', '1', '1', 'Moda, mediana y media del nivel de inglés (calificación).'),
('33', '1', '1', '1', '1', '1', 'Nivel de avance de aprendizaje en el área de inglés.'),
('34', '1', '1', '1', '1', '1', 'Tasa de ganadores en competencias por evento.'),
('35', '1', '1', '1', '1', '1', 'Tasa de ganadores en competencia por área.'),
('36', '1', '1', '1', '1', '1', 'Cantidad de ganadores.'),
('37', '1', '1', '1', '1', '1', 'Nivel de dominio del grupo de estudiantes.'),
('38', '1', '1', '1', '1', '1', 'Nivel de diversificación y/o innovación didáctica en aula.'),
('39', '1', '1', '1', '1', '1', 'Nivel de percepción estudiantil como profesor con experticia en la materia.'),
('40', '1', '1', '1', '1', '1', 'Nivel de percepción de parte de coordinadores como docente.'),
('41', '1', '1', '1', '1', '1', 'Nivel de desempeño en la evaluación de los procesos de enseñanza y aprendizaje.'),
('42', '1', '1', '1', '1', '1', 'Nivel de implementación de valores agustinianos.'),
('43', '1', '1', '1', '1', '1', 'Nivel de implicación con los proyectos del PESA+.'),
('44', '1', '1', '1', '1', '1', 'Nivel de desempeño en la planificación de los procesos de enseñanza y aprendizaje.'),
('45', '1', '1', '1', '1', '1', 'Nivel de desempeño en la ejecución de los procesos de enseñanza y aprendizaje.'),
('46', '1', '1', '1', '1', '1', 'Nivel de relaciones interpersonales docente-estudiante.'),
('47', '1', '1', '1', '1', '1', 'Nivel de compromiso y/o apoyo a estudiantes, en actividades académicas y/o extracurriculares.'),
('48', '1', '1', '1', '1', '1', 'Nivel de puntualidad de asistencia a clases.'),
('49', '1', '1', '1', '1', '1', 'Media de calificación final obtenida en el campo de Gestión de la Formación.'),
('50', '1', '1', '1', '1', '1', 'Media de calificación final obtenida en el campo Autogestión Administrativa-Académica y Proyección Académica.'),
('51', '1', '1', '1', '1', '1', 'Tasa de reprobación trimestral y anual (estudiantes).'),
('52', '1', '1', '1', '1', '1', 'Tasa de reprobación trimestral y anual por área MAFIQUI (estudiantes).'),
('53', '1', '1', '1', '1', '1', 'Tasa de reprobación por materia trimestral y anual (estudiantes).'),
('54', '1', '1', '1', '1', '1', 'Cantidad de estudiantes enviados a reforzamiento.'),
('55', '1', '1', '1', '1', '1', 'Cantidad de estudiantes reprobados en su año de escolaridad.'),
('56', '1', '1', '1', '1', '1', 'Media de incidentes trimestral.'),
('57', '1', '1', '1', '1', '1', 'Tasa de aplicación de Segmentos.'),
('58', '1', '1', '1', '1', '1', 'Tasa de aplicación de Exámenes.'),
('59', '1', '1', '1', '1', '1', 'Nivel de incorporación de referencias PAES en los informes RAAT a familias.'),
('60', '1', '1', '1', '1', '1', 'Cantidad de estudiantes con requerimiento de apoyo.'),
('61', '1', '1', '1', '1', '1', 'Cantidad de horas extras (remuneradas y ad honorem) de apoyo a estudiantes.'),
('62', '1', '1', '1', '1', '1', 'Cantidad de incidencias por área (Social, Académica y Puntualidad).'),
('63', '1', '1', '1', '1', '1', 'Cantidad de faltas graves con sanción.'),
('64', '1', '1', '1', '1', '1', 'Cantidad de casos sobre problemas de aprendizaje atendidos Coordinación de Orientación.'),
('65', '1', '1', '1', '1', '1', 'Cantidad de casos sobre aspectos conductuales atendidos en Coordinación de Orientación.'),
('66', '1', '1', '1', '1', '1', 'Cantidad de publicaciones de información preventiva dirigida a estudiantes y familias.'),
('67', '1', '1', '1', '1', '1', 'Cantidad de visitantes a San Agustín Te Recibe.'),
('68', '1', '1', '1', '1', '1', 'Media de consultas diarias sobre admisiones.'),
('69', '1', '1', '1', '1', '1', 'Cantidad de postulantes.'),
('70', '1', '1', '1', '1', '1', 'Porcentaje general por tipo de unidad educativa de procedencia de los postulantes.'),
('71', '1', '1', '1', '1', '1', 'Tasa de aprobación del CPA.'),
('72', '1', '1', '1', '1', '1', 'Cantidad de estudiantes admitidos.'),
('73', '1', '1', '1', '1', '1', 'Porcentaje de estudiantes admitidos según género.'),
('74', '1', '1', '1', '1', '1', 'Porcentaje de estudiantes admitidos según tipo de unidad educativa.'),
('75', '1', '1', '1', '1', '1', 'Media de rendimiento por áreas evaluadas.'),
('76', '1', '1', '1', '1', '1', 'Media de calificaciones en Ciencias Puras en libretas de postulantes.'),
('77', '1', '1', '1', '1', '1', 'Mediana de resultados del pre test.'),
('78', '1', '1', '1', '1', '1', 'Mediana de resultados del post test.'),
('79', '1', '1', '1', '1', '1', 'Índice de avance de aprendizaje de los postulantes.'),
('80', '1', '1', '1', '1', '1', 'Media, mediana y moda de resultados de la evaluación final.');