"""tercera version migration

Revision ID: c4037c7a9ae5
Revises: 151ac9241bfb
Create Date: 2024-09-01 17:21:00.695400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4037c7a9ae5'
down_revision = '151ac9241bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('grade')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=250), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level_id')

    # ### end Alembic commands ###
