"""Initial migration

Revision ID: f49900c38879
Revises: 
Create Date: 2024-07-12 16:10:38.557248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49900c38879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FORMULARIOBASE',
    sa.Column('ID_FORM', sa.Integer(), nullable=False),
    sa.Column('TIPO_FORMULARIO', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_FORM')
    )
    op.create_table('LINEABASE',
    sa.Column('ID_LINEABASE', sa.Integer(), nullable=False),
    sa.Column('TIPODELINEABASE', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_LINEABASE')
    )
    op.create_table('OBJACADEMICO',
    sa.Column('ID_OBJACADEMICO', sa.Integer(), nullable=False),
    sa.Column('NOMBRE_OBJACADEMICO', sa.String(length=250), nullable=False),
    sa.Column('DESCRIPCION_OBJETIVO', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('ID_OBJACADEMICO')
    )
    op.create_table('OBJSIGECALIDAD',
    sa.Column('ID_OSGC', sa.Integer(), nullable=False),
    sa.Column('NOMBRE_OSGC', sa.String(length=250), nullable=False),
    sa.Column('DESCRIPCION_OSGC', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_OSGC')
    )
    op.create_table('PERMISOS',
    sa.Column('ID_PERMISO', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOMBRE_PERMISO', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_PERMISO')
    )
    op.create_table('ROLES',
    sa.Column('ID_ROL', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOMBRE_ROL', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_ROL')
    )
    op.create_table('USUARIOS',
    sa.Column('ID_USUARIO', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOMBRE_USUARIO', sa.String(length=250), nullable=False),
    sa.Column('EMAIL', sa.String(length=250), nullable=False),
    sa.Column('PASSWORD', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_USUARIO'),
    sa.UniqueConstraint('EMAIL')
    )
    op.create_table('INDICADORES',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_OBJACADEMICO', sa.Integer(), nullable=True),
    sa.Column('ID_OSGC', sa.Integer(), nullable=True),
    sa.Column('ID_LINEABASE', sa.Integer(), nullable=True),
    sa.Column('ID_FORM', sa.Integer(), nullable=True),
    sa.Column('NOMBRE_IDEA', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['ID_FORM'], ['FORMULARIOBASE.ID_FORM'], ),
    sa.ForeignKeyConstraint(['ID_LINEABASE'], ['LINEABASE.ID_LINEABASE'], ),
    sa.ForeignKeyConstraint(['ID_OBJACADEMICO'], ['OBJACADEMICO.ID_OBJACADEMICO'], ),
    sa.ForeignKeyConstraint(['ID_OSGC'], ['OBJSIGECALIDAD.ID_OSGC'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ROLES_PERMISOS',
    sa.Column('ID_ROL', sa.Integer(), nullable=False),
    sa.Column('ID_PERMISO', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_PERMISO'], ['PERMISOS.ID_PERMISO'], ),
    sa.ForeignKeyConstraint(['ID_ROL'], ['ROLES.ID_ROL'], ),
    sa.PrimaryKeyConstraint('ID_ROL', 'ID_PERMISO')
    )
    op.create_table('USUARIOS_ROLES',
    sa.Column('ID_USUARIO', sa.Integer(), nullable=False),
    sa.Column('ID_ROL', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_ROL'], ['ROLES.ID_ROL'], ),
    sa.ForeignKeyConstraint(['ID_USUARIO'], ['USUARIOS.ID_USUARIO'], ),
    sa.PrimaryKeyConstraint('ID_USUARIO', 'ID_ROL')
    )
    op.create_table('ACCIONESMEJORA',
    sa.Column('ID_ACC', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=True),
    sa.Column('DESCRIPCION', sa.String(length=250), nullable=False),
    sa.Column('TIEMPO_PLAZO', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['INDICADORES.ID'], ),
    sa.PrimaryKeyConstraint('ID_ACC')
    )
    op.create_table('ALCANCES',
    sa.Column('ID_ALCANCE', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=True),
    sa.Column('META', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['INDICADORES.ID'], ),
    sa.PrimaryKeyConstraint('ID_ALCANCE')
    )
    op.create_table('PLAZOTIEMPO',
    sa.Column('ID_PLAZO', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=True),
    sa.Column('FECHA_PLAZO', sa.Date(), nullable=False),
    sa.Column('ANO', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['INDICADORES.ID'], ),
    sa.PrimaryKeyConstraint('ID_PLAZO')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PLAZOTIEMPO')
    op.drop_table('ALCANCES')
    op.drop_table('ACCIONESMEJORA')
    op.drop_table('USUARIOS_ROLES')
    op.drop_table('ROLES_PERMISOS')
    op.drop_table('INDICADORES')
    op.drop_table('USUARIOS')
    op.drop_table('ROLES')
    op.drop_table('PERMISOS')
    op.drop_table('OBJSIGECALIDAD')
    op.drop_table('OBJACADEMICO')
    op.drop_table('LINEABASE')
    op.drop_table('FORMULARIOBASE')
    # ### end Alembic commands ###
